# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: swift 
os: osx
osx_image: xcode9.2
swift:
- "4.0"
cache: cocoapods
podfile: Example/podfile
before_install:
- gem install cocoapods 
- git submodule update --init --recursive
- brew update || brew update
- brew outdated xctool || brew upgrade xctool
script:
 pod install --project-directory=Example
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/SwiftyCloudKit.xcworkspace -scheme SwiftyCloudKit-Example -sdk iphonesimulator10.0 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
