language: swift
notifications:
  email: false
osx_image: xcode9.2
podfile: Example/podfile
cache: cocoapods
before install:
- gem install cocoapods
- pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/SwiftyCloudKit.xcworkspace -scheme SwiftyCloudKit-Example -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.0'  ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
